# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 02:53
from __future__ import unicode_literals

import dj.choices.fields
from django.db import migrations, models
import webapp.choices


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', dj.choices.fields.ChoiceField(choices=webapp.choices.Category, default=1)),
            ],
        ),
    ]
