# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 10:37
from __future__ import unicode_literals

import dj.choices.fields
from django.db import migrations, models
import webapp.choices


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='category',
            field=dj.choices.fields.ChoiceField(choices=webapp.choices.Category, default=1, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='description',
            field=models.TextField(verbose_name='Descrição/Ingredientes'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço R$'),
        ),
    ]
